Create Table patients(
      patient_id VARCHAR(10) Primary Key,
	  first_name VARCHAR(100),
	  last_name VARCHAR(100),
	  gender VARCHAR(10),
	  date_of_birth DATE,
	  phone VARCHAR(20),
	  address TEXT,
	  registration_date DATE,
	  insurance_provider VARCHAR(100),
	  insurance_number TEXT,
	  email TEXT
);

SET datestyle = 'DMY';
SELECT * FROM patients
limit 10;



ALTER TABLE appointments
ADD CONSTRAINT fk_appointments_patient
FOREIGN KEY (patient_id)
REFERENCES patients(patient_id);


ALTER TABLE appointments
ADD CONSTRAINT fk_appointments_doctor
FOREIGN KEY (doctor_id)
REFERENCES doctors(doctor_id);

ALTER TABLE billings
ADD CONSTRAINT fk_billings_patient
FOREIGN KEY (patient_id)
REFERENCES patients(patient_id);

ALTER TABLE billings
ADD CONSTRAINT fk_billings_treatment
FOREIGN KEY (treatment_id)
REFERENCES treatments(treatment_id);

--Counts record of each table

SELECT COUNT(*) AS total_patient FROM patients;

SELECT COUNT(*) AS total_billing FROM billings;

SELECT COUNT(*) AS total_appointment FROM appointments;

SELECT COUNT(*) AS total_treatment FROM treatments;

SELECT COUNT(*) AS total_doctors FROM doctors;


--Check duplicate values

SELECT patient_id,COUNT(*)
FROM patients 
GROUP BY patient_id 
HAVING COUNT(*) > 1;

SELECT doctor_id,COUNT(*)
FROM doctors 
GROUP BY doctor_id 
HAVING COUNT(*) > 1;

SELECT appointment_id,COUNT(*)
FROM appointments
GROUP BY appointment_id 
HAVING COUNT(*) > 1;

SELECT patient_id,COUNT(*)
FROM patients 
GROUP BY patient_id 
HAVING COUNT(*) > 1;

SELECT bill_id,COUNT(*)
FROM billings
GROUP BY bill_id 
HAVING COUNT(*) > 1;

SELECT treatment_id,COUNT(*)
FROM treatments 
GROUP BY treatment_id 
HAVING COUNT(*) > 1;

--Check missing Values

SELECT * 
FROM patients
WHERE patient_id IS NULL;

SELECT * 
FROM patients
WHERE email IS NULL;

SELECT * 
FROM doctors
WHERE doctor_id IS NULL;

SELECT * 
FROM appointments
WHERE doctor_id IS NULL;

SELECT * 
FROM billings
WHERE amount IS NULL;

--Building KPI
--Total Patients--
SELECT COUNT(*) AS total_patients 
FROM patients;

--Total Doctors
SELECT COUNT(*) AS total_doctors
FROM doctors;

--Total appointment
SELECT COUNT(*) AS total_appointment 
FROM appointments;

--Total Treatments
SELECT COUNT(*)  AS total_treatment
FROM treatments;

--Total Revenue
SELECT SUM(amount) AS total_revenue
FROM billings;

--Average Bill Amount
SELECT ROUND(AVG(amount),2) AS avg_bill_amount
FROM billings;

--Pending Vs Paid Bills
SELECT payment_status, COUNT(*)
AS total_bills
FROM billings 
GROUP BY payment_status
ORDER BY total_bills DESC;


--Business Analysis --

--Which Doctor  Handle The Most Appointment--

SELECT 
  d.doctor_id,
  d.first_name ||'  '|| d.last_name AS doctor_name,
  count(a.appointment_id) AS total_appointments
  FROM doctors d
  JOIN appointments a
  ON d.doctor_id = a.doctor_id 
  GROUP BY d.doctor_id,doctor_name
  ORDER BY total_appointments DESC;

--Which treatment Types are most Common?
 SELECT
    treatment_type,Count(*)As total_treatment 
	FROM treatments 
	GROUP BY treatment_type
	ORDER BY total_treatment DESC;

--Revenue Generated By Payment Method
SELECT 
    payment_method,
	ROUND(SUM(amount),2) AS total_revenue 
	FROM billings 
	GROUP BY payment_method
	ORDER BY total_revenue DESC;

--Payment Status BreakDown
SELECT 
  payment_status,
  ROUND(COUNT(*),2) AS total_bills
  FROM billings
  GROUP BY payment_status
  ORDER BY total_bills DESC;

-	BUSINESS QUESTION
--Top 10 highest Revenue Patients

SELECT 
   p.patient_id,
   p.first_name ||' '|| p.last_name AS patient_name,
   ROUND(SUM(b.amount),2) AS total_spent
   FROM patients p
   JOIN billings b
   ON p.patient_id = b.patient_id
   GROUP BY p.patient_id,patient_name
   ORDER BY total_spent DESC
   LIMIT 10;

--Appointments Status Analysis
SELECT 
   status,
   COUNT(*) AS total_appointments
   FROM appointments
   GROUP BY status
   ORDER BY total_appointments DESC;

--Most Active Clinics 
SELECT 
  d.hospital_branch,
  COUNT(a.appointment_id) AS total_appointments
  FROM doctors d
  JOIN appointments a
  ON d.doctor_id = a.doctor_id
  GROUP BY d.hospital_branch
  ORDER BY total_appointments DESC;



























































  














  
  

































































































